[project]
name = "pyecharts-django-demo"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2",
    "django-environ>=0.12.0",
    "mysqlclient>=2.2.7",
    "pyecharts>=2.0.8",
]
