# Generated by Django 5.2 on 2025-04-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_code', models.CharField(db_comment='团队代码', max_length=50, primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, db_comment='团队名称', max_length=100, null=True)),
                ('competition_zone', models.CharField(blank=True, db_comment='赛区', max_length=50, null=True)),
                ('competition_topic', models.TextField(blank=True, db_comment='赛题', null=True)),
                ('enterprise_proposition', models.TextField(blank=True, db_comment='企业命题', null=True)),
                ('enterprise_tech_direction', models.TextField(blank=True, db_comment='企业命题技术方向', null=True)),
                ('work_name', models.TextField(blank=True, db_comment='作品名称', null=True)),
                ('create_year', models.CharField(blank=True, max_length=4, null=True)),
                ('is_current', models.IntegerField(blank=True, null=True)),
                ('previous_version_id', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preliminary_award', models.CharField(blank=True, db_comment='初赛奖项', max_length=50, null=True)),
                ('enterprise_award', models.CharField(blank=True, db_comment='企业奖项', max_length=50, null=True)),
                ('enterprise_advancement', models.IntegerField(blank=True, db_comment='企业晋级', null=True)),
                ('final_technology', models.CharField(blank=True, db_comment='决赛技术', max_length=50, null=True)),
                ('final_business', models.CharField(blank=True, db_comment='决赛商业', max_length=50, null=True)),
                ('best_paper', models.IntegerField(blank=True, db_comment='最佳论文', null=True)),
                ('best_investment_pitch', models.IntegerField(blank=True, db_comment='最具投资/最佳路演', null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'team_achievement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('member_code', models.CharField(db_comment='个人代码', max_length=50, primary_key=True, serialize=False)),
                ('team_code', models.CharField(blank=True, db_comment='团队代码', max_length=50, null=True)),
                ('member_name', models.CharField(blank=True, db_comment='姓名', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, db_comment='性别', max_length=10, null=True)),
                ('member_type', models.CharField(blank=True, db_comment='人员类型', max_length=50, null=True)),
                ('member_type_detail', models.CharField(blank=True, db_comment='人员类型详细', max_length=100, null=True)),
                ('school', models.CharField(blank=True, db_comment='参赛成员本人所在学校', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_comment='电子邮箱', max_length=100, null=True)),
                ('title', models.CharField(blank=True, db_comment='职称', max_length=50, null=True)),
                ('position', models.CharField(blank=True, db_comment='行政职务', max_length=50, null=True)),
                ('research_direction', models.TextField(blank=True, db_comment='研究方向', null=True)),
                ('degree_level', models.CharField(blank=True, db_comment='学位层级', max_length=50, null=True)),
                ('degree_type', models.CharField(blank=True, db_comment='学位类型', max_length=50, null=True)),
                ('major', models.CharField(blank=True, db_comment='专业', max_length=100, null=True)),
                ('grade', models.CharField(blank=True, db_comment='年级', max_length=50, null=True)),
                ('enrollment_year', models.TextField(blank=True, db_comment='入学年份', null=True)),
                ('expected_graduation_year', models.TextField(blank=True, db_comment='预计毕业年份', null=True)),
                ('student_id', models.CharField(blank=True, db_comment='学号', max_length=50, null=True)),
                ('qq_number', models.CharField(blank=True, db_comment='QQ号码', max_length=20, null=True)),
                ('address', models.TextField(blank=True, db_comment='地址', null=True)),
                ('team_order', models.IntegerField(blank=True, db_comment='团队顺序', null=True)),
                ('create_year', models.CharField(blank=True, db_comment='创建年份', max_length=4, null=True)),
                ('is_current', models.IntegerField(blank=True, db_comment='是否当前', null=True)),
                ('previous_version_id', models.IntegerField(blank=True, db_comment='前一版本ID', null=True)),
            ],
            options={
                'db_table': 'team_member',
                'managed': False,
            },
        ),
    ]
