# Generated by Django 5.2 on 2025-04-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_areastats_northwestschoolstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='areastats',
            name='subproject',
            field=models.CharField(blank=True, db_comment='子项目/专项/题目组', max_length=100, null=True),
        ),
    ]
